### ISSUE TITLE
Evaluate: On Upload, process excel into CSV

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1872]
We also need to understand the performance of different options to know if the solution we choose is OK.

- [x] Understand what sizes of Excel files we have in Dryad.
- [x] Get sample of different size Excel files in our current Dryad system to test processing on.  I'd say maybe about 20-30 files to test from largest sizes to smallest.
- [x] Be sure we have some excel files with multiple worksheets for testing.
- [x] Karthik recommends Python's Pandas with sheet_name=None .  Does this seem reasonable or are other solutions recommended.  Need to do some initial research and choose
- [x] Evaluate the running time and reliability for processing the files out into individual CSVs.

- Lambda work will need a lot of infrastructure (probably more than the code itself) based on the discussions CDL is having
- We need to return results of new files, probably to S3.  The application also needs a way to discover newly added contents (we don't have wireframes yet).  For larger processing it took minutes (up to 8 minutes on our test data for larger items) and some items were not valid Excel files or couldn't parse.
 
There are still some UX feedback we will get from Rachael and others, though he had some designs for us to begin looking at.

Other documentation:

https://gist.github.com/karthik/8d0cffbf15f76c84d34d83964a6654d7

Please see https://docs.google.com/document/d/1sBzKr-xIVhu9ARZO2b_groLawZekTUNc-zW3OeNcfbY/edit for some more background.

@dlowenberg where were those example wireframes/sketches that Karthik had? (I couldn't remember.)

**Comment by sfisher** [comment]
I wrote an example python script (which I'll add to our codebase for reference later) that simply processes files in a directory.  It will need significant modification but is a kernel of what we will want later.  You can see processing times and things in the attached text file.

[output_excel_to_csv.txt](https://github.com/CDL-Dryad/dryad-product-roadmap/files/9983763/output_excel_to_csv.txt)

**Comment by sfisher** [comment]
Here are some results from the run Python run of conversion.  https://docs.google.com/spreadsheets/d/1VvPgWVn1Q8OBp9DopBGjo8XfDEpZJSmLMQpZC9XFrZM/edit?usp=sharing
