### ISSUE TITLE
Breakup into real tickets: Show contents for compressed files

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1875]
We want to show the file contents of compressed files. The format that Karthik has shows file extensions, file numbers, percentage of total.  It is not clear to me if this manifest includes all compressed and uncompressed files in the dataset or just a preview of the file types for each compressed file.  In either case, it is mostly the same processing.

- [x] Created tickets to back-process old compressed files to get JSON list of files and sizes.
- [x] We are looking at ways that we can integrate this with a curation workflow for creating indexes.  We have some general tickets for that.  ---- Pending verifying with curators that it is workable.

- [x] For the future, we may need to add some automated way to process items on publication if they have not been processed previously.  Adding a ticket to look into that.

https://gist.github.com/karthik/22ff59ad98915e9549f6c31e6224fe88
