### ISSUE TITLE
Add COUNTER tracking for downloads for comparison

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2487]
We need to get comparison stats in our pages for the new datacite process for COUNTER.  These may not meet the strict info in a COUNTER doc, but that is being worked out with the spec.

See https://github.com/datacite/datacite-tracker and https://github.com/datacite/datacite-tracker/blob/main/example.html . The changes from the example are we would change `trackLocalhost: false` instead and explicitly include the DOI and our tracking ID.

- [x] Insert tracking snippet into landing page (but not triggered).
- [x] Trigger on individual file download as it is clicked (to be redirected)
- [x] Trigger at end of javascript "your file is being assembled" process when the download starts
- [x] Trigger before being redirected to the download if it doesn't need to be assembled and is cached (this one may be the trickiest)

It seems to have to run from the page (and we can't just send JSON from a controller) because it picks up some kinds of context from the HTML page in the tracker.
