### ISSUE TITLE
Funder xRef to ROR transition checklist/tasks

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2862]
At transition time, do these tasks:

- [x] Clear and re-import the latest fundref to ROR mapping (get the ROR release and run the rake task to populate it)
- [x] Deploys code to handle ROR for funders (if not already deployed)
- [x] Run prepared funder backup script/query
- [x] Run prepared updating crosswalk script/query
- [x] Verify it looks right
- [x] Regenerate SOLR search data for the new funder facets (rake task)
- [x] Resubmit metadata to DataCite so they have the updated metadata (rake task)

https://docs.google.com/document/d/1svrl8I1yU6ZS1p45pupWSWSVe63m796XjrAEq0hRp_4/edit
