### ISSUE TITLE
Investigate queuing and asyncronous tracking system for zenodo workers/submissions

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#649]
**Problem description, and links to relevant helpdesk tickets:**

Because submissions to Zenodo will take a long while, we need to do this outside the main user interface flow with some kind of process that happens in the background.

This also means we need ways to track the state and things that happen while we're not watching.  In the past we have done this with some libraries that use "promises" for the submission queue.  However, this has turned messy since the processes still run inside our server application and it prevents us from doing maintenance or restarting our UI when it it coupled like this.

We need a better system for long running processes.

**Describe the solution you'd like:**

We need to investigate.  This same system will likely also be used for zenodo code-submissions.  It would also make some sense to eventually move our merritt submissions so they don't run as sub-processes under our passenger server which causes us some difficulties.

Possibilities are:

- Roll more of our own cron jobs.  (I don't really like this idea a ton since we have a ton already, they are painful to manage and I'm not sure this is a great solution and is quite manual.)
- Sidekiq is something many people recommend.  However it absolutely relies in Redis and also not sure how well it saves state if the server restarts in the middle.  Also they offer paid versions of the software aside from the free version and I wonder how much the free version is crippled.
- Resque is another option and I think it also relies on Redis but I believe is open source but without the scale of sidekiq.
- Delayed Job or Active Job may be all we need and seem to be able to use a MySQL database without installing Redis or as much change.  However may not scale up as well.
- AWS lamba is another option, but probably not a viable one since it has 15 minute processing limits which may be too short for large submissions.  It also may also require duplicative work for database models or other things.

- [x] Determine a decent path forward for quite moderate amounts of asynchonous and long-running jobs (I'd guess less than a thousand a day) to run outside our UI web server processes.
- [x] Do a quick prototype to see that a solution functions as expected.
- [x] Add another ticket about asynchronous state and queue management since this ticket doesn't address some of those details.

**Additional context:**
This question requires some research and investigation.

**Comment by sfisher** [comment]
Comments on this ticket and things I've found.

The Rails framework ActiveJob libraries are meant to address these issues and are a common standard way to address background processing for a Rails application.  ActiveJob works as a wrapper around the most popular backends for asynchronous queuing and processing that are most commonly mentioned: Sidekiq, Resque and (Shopify's) Delayed Job.  If using the ActiveJob interface, the backend can be switched out with only a bit of configuration change if more scaling is needed.

Delayed Job is attractive since it saves its queue in a table in the application's MySQL database and doesn't require another server technology (Redis) to be installed and managed.  It also doesn't involve extra worry for saving queue state like the technologies that rely on Redis which is an in-memory store and may not save the queue in the case of an irregular exit or crash.

The Redis-backed asyncronous queuing systems apparently are very fast and can handlea huge numbers of queuing requests with ease, but I believe are all overkill for the few dozens to hundreds or even few thousands of queueing jobs we'll likely do every day (this scale is very small compared to how some people use these systems).

Delayed Job saves queue state to the database (from request by ActiveJob) and a separate independent Delayed Job daemon process picks up jobs off the queue and processes them so they run independently of the web server processes.  The items enqueued can be of all different types and it can contain multiple different named queues for jobs (as well as priorities, time scheduling and other features).  While the application code needs to be present, the Delayed Job queue processor could run on any server that has access to the database and doesn't even need to run on a UI server and probably wouldn't use most of the application code.

I've made a PR with the configuration and a simple example of using the queue to write to a file text to a file to see how things happen.

Some notes & common commands to manually try out delayed job/ActiveJob on this branch.

```
https://github.com/collectiveidea/delayed_job
https://axiomq.com/blog/deal-with-long-running-rails-tasks-with-delayed-job/
https://github.com/collectiveidea/delayed_job/issues/776
https://github.com/collectiveidea/delayed_job/wiki/Delayed-job-command-details
https://guides.rubyonrails.org/v4.2/active_job_basics.html


RAILS_ENV=local_dev bin/delayed_job start
RAILS_ENV=local_dev bin/delayed_job stop
-n, --number_of_workers=workers

StashEngine::ZenodoCopyJob.perform_later('my cat has fleas')
StashEngine::ZenodoCopyJob.perform_later('my dog has fleas')
StashEngine::ZenodoCopyJob.perform_later('my rat has fleas')
```

We will need to add additional states and other thing to our database for tracking since ActiveJob is really just a work queue and doesn't automatically track application states.

We really may want to move our Merritt submissions to use something like this rather than the expansion I made to David's home-baked queueing system which still runs inside the UI server processes and can have problems if the UI server goes down at a bad time.

**Comment by sfisher** [comment]
Added ticket #650 for tracking status which I think is separate from the work queue.  It may need more detail as we go forward.
