### ISSUE TITLE
Status tracking for zenodo 3rd copy replication

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#650]
**Problem description:**

We need to replicate latest published version to of each new published dataset to Zenodo's storage and track the status of that replication and storage ID.

It turns out we will only be doing one version in zenodo, but they do keep entire history of file changes over time.  So in theory we can get the versions of files back out.  This is good enough, so we don't need to create new  dois for each version.

**Describe the solution you'd like:**

After looking at the queuing solutions, it's clear it tracks just the status for the queue to do the submission, but we'll need additional information and processes to handle status checking and similar.

- [x] Each published dataset can have a copy in Zenodo.
- [x] Ideally a table with a foreign key to the resource_id (to know which published version and identifier it belongs to).  A dataset (identifier) can have more than one published version stored in Zenodo.
- [x] Track the returned identifier_id (DOI) in Zenodo.  Each zenodo submission gets one.
- [x] Track status: 'enqueued', 'replicating', 'finished_replication', 'error' and also any error type and as much detail as possible where it can be easily found in the database instead of digging through log files.

**Additional context:**

This is really about the overall status and management of the replication jobs.
